user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Ocultar de la versión de Nginx y del servidor subyacente
    server_tokens off;

    # Límite Nivel Dios: 20 peticiones por segundo por dirección IP
    # Creamos una zona en memoria de 10MB (api_limit)
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/s;

    # Seguridad: Bloquear cualquier ataque de inyección de payload enorme (max 1MB)
    client_max_body_size 1M;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    # Resolutores internos (DNS de la red puente de Docker)
    upstream frontend {
        server frontend:3000;
    }

    upstream backend {
        server backend:8000;
    }

    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        # Eliminar headers del framework
        proxy_hide_header X-Powered-By;
        proxy_hide_header Server;

        # 1. Todo el tráfico raíz va a nuestro Dashboard
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 2. Tráfico /api va al Python y le aplicamos Rate Limit Duro del Escudo perimetral
        location /api/ {
            limit_req zone=api_limit burst=10 nodelay;
            
            proxy_pass http://backend/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
